apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: system-namespace-exceptions
  namespace: kyverno
spec:
  exceptions:
  - policyName: "*"
    ruleNames:
    - "*"
  match:
    any:
    - resources:
        namespaces:
        - kube-system
        - longhorn-system
        - monitoring
        - kyverno
