apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:S6xm0uNu8K0APAce,iv:FCBVzwAG6Wj++PP5sKLTSdS7reVk78vFqYvEYNRzK7Q=,tag:KmGHcpgtGLzo2SEz4NX/Dw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:v4vaA86/tOhN3AtQfntC9Q==,iv:9/cLLOJoN2lT6ldtKGnDV6V2mBYgIiNJbofG2JrtYng=,tag:oQbBu9y35tIsZv1USs6xZA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:o+Nz3/+EmuNa+lx4,iv:R4eQZeO/4XNnal+87rQy0VBbECjUS6KHg7FnrisLmyY=,tag:tdut0NEF5FIQAuMctI5O+A==,type:str]
kind: Secret
metadata:
    name: keycloak-postgres-secret
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMWp1ZThVOENKRVFNWFVJ
            Rkowcmo5OW8xeHZmMlBYZFZxdW00eUloRUhzCnRTSU9ERk43emU1UUhpZWhXWTVM
            UCthOGIvOWhlWmtQYmNyTnljdlh5bHMKLS0tIENESnJ6YitRNWNSUC9ZSWRLMWlG
            MlozdkczVmJaMjlNZW8rcWQ4S2F6ekkKkxVjxzhA9oyXfxAuAbn7lJzOlfez/w3n
            93NrtdqHFy8OeQolAblJP2oO2E68bmj+Nmh416GBb4x46YbVf7EYmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T05:18:36Z"
    mac: ENC[AES256_GCM,data:DZhm35ThPE1NpNUY/zM2TPYR3k+rLDXGGexBBcqSCbv3HGoYxcKgqNe9AicKYQp8LTFYn+T7hFOcr+TQRKFTk8a96waPDoNAWheC7Kv/D5WNZLrQuCB+xDQIbveT/CTtxv0rL7LYRETd9swIkPX2fmJsckPOOmchYT3AhpPmRbo=,iv:uI9CkQq+a1hW4AQQMfzJ8pX7vcNnUoU8iQvjSZUkYwA=,tag:sXgS6bdGoLI9DT+6h/XErQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
data:
    KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:NODNA9//kV4A2Fcg,iv:YLoEqwLY67DvianKWnXVui7nFLsLQquu7rLFpqjMVW0=,tag:ByOJ1IhikCdApN+cpzQ28A==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:K3M9EeY06094xUkT3FxIJxh/l+8=,iv:bF6cIdwjtM8ZezGs86RDjXnB+CBxfcTEV7c8JuvdcJY=,tag:WFXKKdhjvZwxjEgH0WhuGg==,type:str]
kind: Secret
metadata:
    name: keycloak-admin-secret
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK213V3Z4K0tkeGphSzNJ
            YW9FZEQrbURjN1Ixb0RBTmJadkFGK01DZ2x3Ck1nSlRlY2h1bnIvMFp3V25tcURV
            OXl3OVBsaTM4aEpGZXMrU3djWXc3ODAKLS0tIG9SamN1TDdYaFYvTjlrc090RjhK
            aDNDRHJsYW9KUGpZYjNmcGpSbEFETUUKVXPHdXPx1O4D/vbOO8iIAxJYTmI37jTF
            hSjJuN3t2AVgI9I+HTFeYd+gJ/PZ1PMta4U6YjXNJPqnZv6OjgMKdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T15:07:57Z"
    mac: ENC[AES256_GCM,data:9jD2jsQrxJTeWdsDEyvm7aP9Z4FZQdbs5ucbKTcTEFZsrkPw6kDLOfYCnj65STFDSZuOvzTzJay9qSCScmmU3QqpUXXGtAmpCJwoIcZJWHLC9FasdcCMxqA7KoMu10xZ7aFRRq3HtvzwjE9K3q+1Ep1A5e3F37KAkiOIcXXzVgk=,iv:sfZkHuWkILY55baQ/uzVcXyBf+W0nkqH1nwIOVzmSTE=,tag:OGz4angYwuc4cQeEiErkrA==,type:str]
    version: 3.13.2
