apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:S6xm0uNu8K0APAce,iv:FCBVzwAG6Wj++PP5sKLTSdS7reVk78vFqYvEYNRzK7Q=,tag:KmGHcpgtGLzo2SEz4NX/Dw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:v4vaA86/tOhN3AtQfntC9Q==,iv:9/cLLOJoN2lT6ldtKGnDV6V2mBYgIiNJbofG2JrtYng=,tag:oQbBu9y35tIsZv1USs6xZA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:o+Nz3/+EmuNa+lx4,iv:R4eQZeO/4XNnal+87rQy0VBbECjUS6KHg7FnrisLmyY=,tag:tdut0NEF5FIQAuMctI5O+A==,type:str]
kind: Secret
metadata:
    name: keycloak-postgres-secret
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMWp1ZThVOENKRVFNWFVJ
            Rkowcmo5OW8xeHZmMlBYZFZxdW00eUloRUhzCnRTSU9ERk43emU1UUhpZWhXWTVM
            UCthOGIvOWhlWmtQYmNyTnljdlh5bHMKLS0tIENESnJ6YitRNWNSUC9ZSWRLMWlG
            MlozdkczVmJaMjlNZW8rcWQ4S2F6ekkKkxVjxzhA9oyXfxAuAbn7lJzOlfez/w3n
            93NrtdqHFy8OeQolAblJP2oO2E68bmj+Nmh416GBb4x46YbVf7EYmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-06T05:18:36Z"
    mac: ENC[AES256_GCM,data:DZhm35ThPE1NpNUY/zM2TPYR3k+rLDXGGexBBcqSCbv3HGoYxcKgqNe9AicKYQp8LTFYn+T7hFOcr+TQRKFTk8a96waPDoNAWheC7Kv/D5WNZLrQuCB+xDQIbveT/CTtxv0rL7LYRETd9swIkPX2fmJsckPOOmchYT3AhpPmRbo=,iv:uI9CkQq+a1hW4AQQMfzJ8pX7vcNnUoU8iQvjSZUkYwA=,tag:sXgS6bdGoLI9DT+6h/XErQ==,type:str]
    version: 3.13.2
