apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:ci8qwcNVeS/vMb2odW9F6q1Bg6TdSzm8JdWW61Vvs7ADvM46n2ie1DmmmKWnmAa3hzUKOgbmyELMPq2IJQR0qgrpzAtNXBv/,iv:ok3NnGb0sGDHmRCT+KDoOjgOdaqhF0Y4SEhDL19P3Lo=,tag:tcPp5bF+8L7701dwq8wHyA==,type:str]
kind: Secret
metadata:
    name: cloudflare-dns-api-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNk50WXp1TlBaaG45QkEy
            RTduZkh6aTMramRmR3FwcjhreXhBV0NBN3ljCkNLVkVZYW0ra0doa1lId2ZJZnJq
            cElIbVlrUGJtcEI1amlveGFNY3hHYlkKLS0tIGZhYXdWSkJpRHVCa2I0eTFQWmJI
            NlFxOE4yRWNqWDZIR3VxSUZnQ2c2REEKLZF7fXL3BuypVwGjGkqqtsAqpp4hYH1B
            YZeTyrAodnQC+NuJnAp8KvYVyJ8lq9wEXrk7ljpNhc3i3pQ0sPinQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T06:49:16Z"
    mac: ENC[AES256_GCM,data:mb+rG++1K/Z6vdTfUVL2GmDGYBr5hrrSSgTUzIjCEcgHjqjDqA5A2Uu8UrIKF18mLVKbg8DBi4xtn+WNiyrprfNlWMzX9kNC6g8GbPAvO4gfzztIflaekTjO4uxR27pEDebLE3IkxS6yVdhfAz6jlU23g8IZ1Fj94Rk8YF0jwpo=,iv:b8jeSyseAqh1hRsreLVBAo+C7y2M5HdyR/snobX6nbI=,tag:2KPf4AegSFyb7sZ7TIEXrw==,type:str]
    version: 3.13.1
