apiVersion: v1
kind: Secret
metadata:
  name: staging-edvsul.org
  namespace: longhorn-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/staging-edvsul.org
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
