---
k3s_cluster:
  children:
    server:
      hosts:
        10.0.0.78:
    agent:
      hosts:
        10.0.0.77:
        10.0.0.76:
        10.0.0.75:

  # Required Vars
  vars:
    ansible_port: 22
    ansible_user: admin
    k3s_version: v1.34.1+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--flannel-backend=none --disable-network-policy --disable-kube-proxy --disable=traefik --disable=servicelb"
