apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: kube-system
stringData:
    client_id: ENC[AES256_GCM,data:Qdt8kd5R8bAxZGZwERJbiF8=,iv:mX8o3yNc4yY89yKT9taG8w/XXq12MmeTLsNqzOlnLjk=,tag:Q5KyLrkH5MDNG5hO5XTaSw==,type:str]
    client_secret: ENC[AES256_GCM,data:oYBXdHgCImbiGTuFTlopN6F2cZbAWRI0qwzhc/iDc2z6oI2NuEBT9fSL5tBMgNL33bn8s5FT45z16pv4pFBIig==,iv:FonnhgNg83fOq56Y/DZK5YmnkL06GcpKJHqCpIXuobo=,tag:tDCiwuHc0OvZOf4Un7klGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRnV1SU5FZHBsdXo5UURl
            R2tiQkgxYTN1bjhvMFppa242b2EvNFRMYVJBCmd4UjJTRmRjeGMzMnJ3UkJwYjZl
            UHZtNENqUmpkajF3UXM5WXovcDFkSjQKLS0tIHZQT2lkMG1aTi9uUkwzM2tpaTBq
            dnpUR2N6VGl2aDJtMUg0MUR2SUtud1UKxM/TFG6KbVItTVks495zi916PGQfSap5
            gkRl4QcLf4RYOM+Qc8nUE0WptRVeHhrl60D7Ryh4/hqb0MrkF30akw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T18:14:52Z"
    mac: ENC[AES256_GCM,data:DCkovScqM0U3zTNfzjHbMwpWQCnTSK/7EognH7KKtwHOJTxSGRO5P4sF7dN2QYMIGdZJMIQJCbCCPuEQoBMC97k8bgY1+NQCTPRPINfn3EX+Ci74BUpRVr9SXHiJnPJ79S9KGgV1I6TD4Fi9zDGXac3zSLj7yU/2DyB8b06PwpA=,iv:snuzwduUtV9yeBCRP9SBejHcV0D/UGrhAz2meCqRmYU=,tag:wke77vNiWmUA0GOlRiAYTA==,type:str]
    version: 3.13.1
