apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: kube-system
stringData:
    client_id: ENC[AES256_GCM,data:WyqLLGwvdluYBIx5eITE6jk=,iv:gFjXYk0hiIA/DI1jnyQJFt9lNjQzO29eltbRIFPXgeA=,tag:8yiIFbxxp+7caDJSs11awg==,type:str]
    client_secret: ENC[AES256_GCM,data:8zGLlBVWv0edi+ZOOI9RsZ+IWPyv2Hs4uchl1FVzxv8BbIEZYCF9yXCiyqciN1k50XC6tNbvdfjAVZ3fJi6/sw==,iv:DQr5x5LF77xriXkkez/XIhKY5FkJliYEuXxrrJKIIqM=,tag:gaf4GyJn1XJbSBTNvGiwLw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYM3YyaENaZ3lEd3JaaFlG
            aFJXSGtuMmdqSHpLVjlBK1dzZEYyWnZWQlhrClk5ZVE3dkhjTVVNN1g2ckliaStj
            d2U4MzZkQ3ovQkhYMEJTTkthb3BVRjQKLS0tIG1EYksrVkpXRG44cmhwNDhnUlhU
            eEJMbi90YTlJYzViM1FYUVJxTXVNZGsK6VHvF07QLTGs8+aNGLJeUzFc+9yreRi9
            422UhwMUaggK8N0knTspSN++/U7tcUeNwLx+qTW7CDRZdTtxoWRLKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T18:31:07Z"
    mac: ENC[AES256_GCM,data:ogKtFPO75JN9Zl9xmW34uG+0RTuFwSREdJn1RpEHnsWm5bYF1WkfkIZ6di+TCv13DftZmIQ5mbDRS40AskMdbD56R93v7/NoWZWl/zX2TCR2K+TDjRgUvRxVXeFLvLsfthkRyicRSxj6yL38NKneRF5FMGr/oM9Lq9RiKg8Rv/I=,iv:sMb3mAtEFWPUEOjj3+TkaItYbCKTYWvfZol/ZY+sV7c=,tag:rP+rkpkdPSH/b19li+jLog==,type:str]
    version: 3.13.1
