apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: kube-system
stringData:
    client_id: ENC[AES256_GCM,data:b0uMxKsKyd5NhSML9k5a42g=,iv:BwaxKALIR2unF3z30S7YulqlhvGN2Wyret4dzqt3+HU=,tag:vMx84G42RnGuyQfWzCGSXQ==,type:str]
    client_secret: ENC[AES256_GCM,data:ly9m4mE+73J8M2CeVL4zv7G0xe7+cbha7BKX8+v/zzPMXm67BbFkMjVtFDlNox64q0DOueKwaly+cs2DQsHq,iv:jdc4BKFes9gD3hFznblR8KpLlv//UEykJ5eaGWsqwMI=,tag:C9wqpOm1eFFPs6dj6e0hhg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRUhnT2pSUW94TnExUEQ5
            TmdMVFNvSGNSWkFORTBsZlJCaUFORnZxUlNNCmxxQ2pzd3hlRDBoVTkzMkdjZzZP
            NlFWSW5rRVpuVG93MUtNVythMzBFSXMKLS0tIEw2bkV5VEFGQWV2Q0wxWVF3SjVq
            YXVtYmpXdHlpRFNLN0wybG9MNEFML1UKxqwqDSt6j9J1q6JRBZngw+4sVvYiPDF/
            FMERyjq35NIi4gXH8EH2QWusgF5WFlF/O7mSpUd3sbTVi7R81dbnrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T18:03:25Z"
    mac: ENC[AES256_GCM,data:KiQWSiBGuEu7bw5GePuaum+fsL4GIgGMcy3rLrwFSuG12yOaVLEnWxEwrSEgJWgpheAWA2QScTELtpxotufPAGiZpmQq0q4MJBmrD3lQlJdzmiUNFjrDvPK6PRZAxGVzZcYTOI++kolfPgECP1LoGJbcbmGe8Hislhd0YUlRo6o=,iv:MMGf7CU15JZFE72/npG7Dd1L6w5OCGewnxyeTUY/gtU=,tag:ypHPHb6hH54pvEQo+OfwgA==,type:str]
    version: 3.13.1
