apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:yfB/P5+aTne36i1TPYVKRpMbvC6lycNvImQmxBsgGmLInLEojneMT2Y8tKBSUf2qh1uBisszMF2o4SyzPSWgT8tZdwDf9+igouUBPa2U3FzZ44luTkrO4zC9YXT2RgoFjqm2U1iVN+GqUiGenXa9Sfrncnsg5vJnTxhHsZzn3K5Cn7Q5qWs1FObF0NQP5St57EhT25hhSDa6yMEGOAXgVLphEhnyY4ouO/UllYJUTgH8fdRMJSrNYNc49NkblsuW8mU4aGOhgwsnfOc3D0T8zwmkJ3MmMIRk6ilkmoi5bUUsY+55tZWhWPFdaEU=,iv:iNdzP1HenQSTr87ZYV1TfjNW3qT9w+ThQ8AyBg8iFTc=,tag:8AhM7gLc/puo3se65j5aVg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZlVpMXlxa3hudVh4RTVu
            R0FCdWtNMU5iSmdqK2pCdEd4YXMrNUo2N2tzClBzQlJsR0xOSkZsOVVJYVdRdEdM
            Y0wyWVVXcnhZZVhXY0RBZkZVMDZKamMKLS0tIG43UklYbW50aTk5bkEvQ1VMRUJH
            UzF1TUl2S1VWTnV1emJZdXh6bWk5NTgKu8BunXPio+7Kl8crt7ftzRBsxjwKLekL
            ExhwOS/4KYlFzdqW5NqJCkqqLUzCrHDpRmye9HziBXbKXQqgI3moSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T19:16:05Z"
    mac: ENC[AES256_GCM,data:QJS5hDnEMMhLDsiQ9M6/96bOOR89eG3r2bZYZUrcvL+UziLAgK2wULVboQYgle3ORCvhjum6qxtYlVlRy7G8GCaP136yb5tKD0H+5i7+QICCpRzMybJTF/pRyHIOouSXD3S9t/xNZfaV+sv3Rp1sSMJNk1KGDbzm53HpwmJFIeU=,iv:fjjwMmFZJe6uk1EvhwGnOS/tZmOQl1MjPAUdfjTEUNQ=,tag:SGpjtKZrM0xZYDL3rEl/rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
