apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:8EJ19KIO6czwfJlj8YC9xweKbwfzPih9awATuY9/pYmuZZNzoZPQpqhGt1HdpAyi46jlvwFaEQ5+cGIW4MJPYri3p8pi0ANYaVZ1ErU0kJChR/i5mQmJMwGwbyrx9fBUiFWdw1hgkfVfsa7KAJxRii3VSkMhdROidLoNnBUpznagQIiW85HyfztSusfncTsEWU0FWRgoxVWaxawIwI4GM1yziuuYh5MtSQCPI+jzdoqF3hJGyp6YZEgdvCbJdTwCwIPDNUwPUuvaWgwgDxjRX1psLVrKtCKBLaNPzMirfSPG3pJRI+9tCPVv1ps=,iv:0nBAVvDpTVpHgTc5eLxYoQe4v/vVTphkF5yUh4Q5Ut8=,tag:mQ+AZsOCiNmTpGaPHiq8Pw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0xMUE9SZ2IzRGlFempS
            MkpCMnY5OU1wM0tFRzVOeTA3TW1ZSkxNT2lBCllUZVpla1ViMnN6VnVNbFZKTlpD
            eGkxeXVKMXBVZmRrMHRyUU5FMDBrajgKLS0tIEFnQWp1aHl4Qkh4TW5qWUhHS0I1
            SkxwVHBEbThBSjV5RGt0ZzBGeVhzUDAKkUdCfZJulxKL+jpg/omdF6qvx0TN5btv
            HXdT7x6oMrnRA6gOvooZU477ayUMllIvtMVyOfBLfQX42o6k5Qsb6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T19:01:52Z"
    mac: ENC[AES256_GCM,data:pMyxENCI0Wt1xg4Zk2cmKR/XWzc4DQco4XxK7FaFMDZBZsK/9CPBEYdHCPeuLG2yneiw5mTSDc74UdywUVnv1SLe+Jjy2jL8DqpziyAzYoOwlCDhMFIErdC9T0hsO2IGMit4RlY+aquRuFJWPh/ZurthdTuJKpJpXVkkCY7Xj7o=,iv:tKBSSn+OGW00cLnRrqhiqO3XCpBug7vEJdH3sUwrxXA=,tag:KZB6G5s5PA4UfrU9y0pxtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
