apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moneymatter
resources:
  - namespace.yaml
  - secrets.yaml
  - tls-secret.yaml
  - statefulset.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
