apiVersion: v1
kind: Secret
metadata:
    name: moneymatter-credentials
    namespace: moneymatter
stringData:
    APPLICATION_JWT_SECRET: ENC[AES256_GCM,data:8JfiuaJ/+MoXegqRxjRNcHoNDQyNFrG7EFsXjPJrzYsg05IGLvLdyBDCjykkRtv5/SWW0mVcULfvNni+ApEBcQ==,iv:7IFYuQ8NK0AsXKpewyg2HUIpJoTqLnX/Gp0oEFijwaA=,tag:SK9N9tUNjhpR4xa1h2PnXA==,type:str]
    APP_SESSION_ID_SECRET: ENC[AES256_GCM,data:z1n0bjeO3LRvi86g0MI2j9hg5kduv6bJs4L5IzQ4vOmQQg4kVSk+HUacVnspZdq/Q85Z5FkRUBxwVcmmHAQyRg==,iv:88O3y5rQ+8qh3qjyXFj/ncauS/j+GAdHUC64vZa8pLo=,tag:DxrF+JHrxSPovy/g70/afw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:zWxWqf7RD8Hs3VK7+GFwemB5m0SJBLEWZK49qV3pRn9CLAOSwR/fCVMVbRECuFozNOoH/Ykss4+UroDl9I7lpw==,iv:q/A2tHYZfYCzn0QRcNxYdnagXy3gDermxvlqcOX5Q/c=,tag:KVxYHIpik9R7+VVQStvStw==,type:str]
    APPLICATION_DB_USERNAME: ENC[AES256_GCM,data:+YKxfkRNpjUupSA=,iv:7Kjwoi3WSkD66A5ApAaS98ap0ne5Nw/LGzoqbbLBoU4=,tag:XdvXf9boYz97K3NwTyEtsA==,type:str]
    APPLICATION_DB_PASSWORD: ENC[AES256_GCM,data:y+7e23IIendWF2R0KbvOJNUhB9h2nk5V3wWe9w==,iv:2S6dbxwdpGcevgpNx/SwXalzp1unuJEz3BoEPj88yKg=,tag:3Q81AGGH2PYcbgp1ozqILA==,type:str]
    APPLICATION_DB_DATABASE: ENC[AES256_GCM,data:6plrsK2RLOFYzDo=,iv:zHqttrCu0scRdM/outiI7bCiHo34fDE1OWqriDekPAc=,tag:XI2BGlPqe/b2nAST00G/oQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNVM2eUg2Wi9TblZKdUFH
            NEpHQUVjaHAwcjNFQXU4YUdqdGk2WUhCZ0RjCmtZc2VCMWRUYXdySjJCd0M1d3d0
            dEpVMzhXbTlxakRnMVU2UGxBVk9zUDQKLS0tIHhYMU1PVEt4QU40VUVTQk54RjVk
            WEpjOXNOTnJocUZlZFRFR28zZXp6Sm8KpuMS01YBVJ7rULHjg3zBvTQKu0l5IOOw
            7/FW9tXRxtfKviYfm6u5o0IC5NAjPJCq+WqBSk4w0Sv/u/ZTvbOBgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T11:52:26Z"
    mac: ENC[AES256_GCM,data:oVJ4OJk3jHq0RBO+GgNNedDClXX+gnhpwpZMp2D1L2Iq3wNDO05JK3Gs90wR6gy0rvbrcHp2WpGG5LW4za61A/Ie1+sJ0DmmSaesFebPzVSlzopUadbSzl2FKPovfAAUevDTVJNYWtYpBOst7BE/9pcM7ICEiCYsi1utkCzm5bY=,iv:3WtLhu6BVAYgDh6MnktxAT62HESTKGLkTXdwC2HpWcY=,tag:EyFuUilT7gfvDS6lnUDTfg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: moneymatter-postgres-secret
    namespace: moneymatter
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:b+J8JBt+cIjLoU8=,iv:d+5Y7C18xTmzlm8l/+zu/xc5JNe+g4j7d+K8aOhOXq4=,tag:El//1jOIuGkF7mg+WD15mQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:QLnSIPfhQ3ifSx69MZcUVCb+7C0dDRyiEq7/+A==,iv:MDeDZXMCTYe1kpkr2GGZPLyV1ynBupuyZVqciz3/ROA=,tag:lyRtIKqFPbV6Cq9IJRZydQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:WOaBDz053f4CARA=,iv:YfelFmg8sMymV/5eO7+NwP6I+iyTTyEZufFffxSLAiM=,tag:gl1utYZjlOWC8QpQCV+Bww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNVM2eUg2Wi9TblZKdUFH
            NEpHQUVjaHAwcjNFQXU4YUdqdGk2WUhCZ0RjCmtZc2VCMWRUYXdySjJCd0M1d3d0
            dEpVMzhXbTlxakRnMVU2UGxBVk9zUDQKLS0tIHhYMU1PVEt4QU40VUVTQk54RjVk
            WEpjOXNOTnJocUZlZFRFR28zZXp6Sm8KpuMS01YBVJ7rULHjg3zBvTQKu0l5IOOw
            7/FW9tXRxtfKviYfm6u5o0IC5NAjPJCq+WqBSk4w0Sv/u/ZTvbOBgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T11:52:26Z"
    mac: ENC[AES256_GCM,data:oVJ4OJk3jHq0RBO+GgNNedDClXX+gnhpwpZMp2D1L2Iq3wNDO05JK3Gs90wR6gy0rvbrcHp2WpGG5LW4za61A/Ie1+sJ0DmmSaesFebPzVSlzopUadbSzl2FKPovfAAUevDTVJNYWtYpBOst7BE/9pcM7ICEiCYsi1utkCzm5bY=,iv:3WtLhu6BVAYgDh6MnktxAT62HESTKGLkTXdwC2HpWcY=,tag:EyFuUilT7gfvDS6lnUDTfg==,type:str]
    version: 3.13.2
