apiVersion: v1
kind: Secret
metadata:
    name: moneymatter-credentials
    namespace: moneymatter
stringData:
    APPLICATION_JWT_SECRET: ENC[AES256_GCM,data:k012YvtMKlGzjbN9njS5tLMur4lwkeYjQBXyDk1SCEyGATlCDDQslaE79jFsmEiwdwvpiHFXqvhgIjJ6YkH57Q==,iv:BWzuC19d2cL0TqNE3YFs/igeCHVKTzqGx778IHXL71A=,tag:XeYs0MTIpBKI9hzJJ60r4g==,type:str]
    APP_SESSION_ID_SECRET: ENC[AES256_GCM,data:BPf5atpirXVdpo63j9fqJzgvG1BZtM+BpPWQ+4COO1bnKhkBtwUQEihx8buFICX3a1os/Rax2lUBb/6LL5Rv3w==,iv:LSAK8Ry1HRrros69hgDYSy8tcGJ9PzOeNhibXLRfhZ8=,tag:LyLQkDhSO1RzZ9YjcV2EWA==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:8LHXq4RQ1hTgNB0Uyj9BfwntWyA8vzl3H1lBUQfvahPZaR5b1RCinifaAnG1X3popyUBC0dam936XXYKuguWeQ==,iv:lOPjfsxLoOMMe8OJWFbrMF5BNNDM8w+3DSPon06pfTA=,tag:Vl1DsD0dosLhNpmAZq0Avw==,type:str]
    APPLICATION_DB_USERNAME: ENC[AES256_GCM,data:FM8CwhRVNeH+4b8=,iv:2GrYsSCWMCeTR78tvqI5fAI3UgcIqEGCtmYwnFlxjNU=,tag:CydkHKRkUNG5VFGqapEWrg==,type:str]
    APPLICATION_DB_PASSWORD: ENC[AES256_GCM,data:wmBacjAjIta8Y4MuSW+Y259lJ26sOjDRXo/0mw==,iv:82ZFCWPmee7l5Xco3csyyde42M/miTCJYzUCfEWOY94=,tag:ZkcnupmmIP54F1blbq2iIA==,type:str]
    APPLICATION_DB_DATABASE: ENC[AES256_GCM,data:lAVxa7eV+TQGoDY=,iv:JHvA+igwzzK+RRbkwFsjDR9OpcgzGHiy2iIbPoefLIw=,tag:jFv6qpZ2BOEpaNlSxCLWKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RGo5QnJ2RlE0RkZpbk9C
            TDZhdldDV0xta3c5bzlsY1pqYUIrTjZ1WURnCkE0TVJZM2FlUjNxMjgzM0RSTTRR
            ejNrdXQ0bitPeDV5OG9MbjJQYmF0czQKLS0tIDJxN3FZKzZkdktQL1pqZWg4dmU4
            YWdLeXFHaURpRVVyYUdqUGRQbDYzRFUK9VVuvpUvGCzZnwnNVkljyiV8VGNxjlFL
            8l9vYrUsL5MQFKpEjSHvs/urCWzfSjEULEwli5++sUSldycu2TK9ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T07:35:21Z"
    mac: ENC[AES256_GCM,data:aNdcQIERohtF2+dWJ34BHjG4v0kkqaHBdlgCLRhIPebLh5PkHuCVEk2TxorS0hrH1Ek7XbPSbXlf47p4qtdUDegKyXDDNaeWqapzNgX/oMyyLqQx1Pe8myUi0Y8Tjvtjhaqs8cTQGd5+ddBzcxJj/dQ5WksZjC6a+NyNgl0cnL0=,iv:b7hJDZ/XLTyvNTpZ0KkGUZBWIZLGFA3PAUbyerQvf8I=,tag:FiwCkIYnQA0NtfG0niwchg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: moneymatter-postgres-secret
    namespace: moneymatter
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:lflVCe+zcZj3/vg=,iv:A+CvRBushIO+vDpM1GHKSRrF9rfIxfJO1Z5aYZHir0U=,tag:tV6HWSfavbv/tOFITNQivQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nJ4b4e/IUWOF3eFzAD4IinZ4UtlMc1kDckT++g==,iv:l7ZGxkqQizBlYky7x+nrpG3YT4L52oIfQx7eTYtAFpQ=,tag:zzM+Hpl1CCxokfuQnL5CyQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:JX053uVfU3bJks4=,iv:XW6cj1OWkJjPmxaHvz9NkXYfyVRhrCu6s3GTufZiIZI=,tag:5kUretCN+XI2613K6CXCuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RGo5QnJ2RlE0RkZpbk9C
            TDZhdldDV0xta3c5bzlsY1pqYUIrTjZ1WURnCkE0TVJZM2FlUjNxMjgzM0RSTTRR
            ejNrdXQ0bitPeDV5OG9MbjJQYmF0czQKLS0tIDJxN3FZKzZkdktQL1pqZWg4dmU4
            YWdLeXFHaURpRVVyYUdqUGRQbDYzRFUK9VVuvpUvGCzZnwnNVkljyiV8VGNxjlFL
            8l9vYrUsL5MQFKpEjSHvs/urCWzfSjEULEwli5++sUSldycu2TK9ig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-15T07:35:21Z"
    mac: ENC[AES256_GCM,data:aNdcQIERohtF2+dWJ34BHjG4v0kkqaHBdlgCLRhIPebLh5PkHuCVEk2TxorS0hrH1Ek7XbPSbXlf47p4qtdUDegKyXDDNaeWqapzNgX/oMyyLqQx1Pe8myUi0Y8Tjvtjhaqs8cTQGd5+ddBzcxJj/dQ5WksZjC6a+NyNgl0cnL0=,iv:b7hJDZ/XLTyvNTpZ0KkGUZBWIZLGFA3PAUbyerQvf8I=,tag:FiwCkIYnQA0NtfG0niwchg==,type:str]
    version: 3.13.2
