apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-egress-example"
spec:
  endpointSelector:
    matchLabels:
      pod: cloudflared
  egressDeny:
  - toEndpoints:
    - matchLabels:
        app: linkding
