apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-cloudflared-to-linkding"
  namespace: "linkding"
spec:
  endpointSelector:
    matchLabels:
      app: linkding
  ingress: 
  - fromEndpoints:
    - matchLabels:
        pod: cloudflared
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: "renovate-to-github-dns"
  namespace: "renovate"
spec:
  endpointSelector:
    matchLabels:
      pod: renovate
  egress:
  - toFQDNs:
    - matchName: "github.com"
    toPorts:
      - ports:
        - port: "80"
          protocol: TCP
