apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-all"
  namespace: "linkding"
spec:
  endpointSelector:
    matchLabels:
      app: linkding
  ingress: 
  - fromEndpoints:
    - matchLabels:
        pod: cloudflared
  # egress:
  # - {}
