### Reflector copy secret to the target namespace
# kube-system: consumed by the hubble-ui Ingress (hubble.edvsul.org).
apiVersion: v1
kind: Secret
metadata:
  name: edvsul.org
  namespace: kube-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: cert-manager/edvsul.org
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
type: kubernetes.io/tls
data:
  tls.crt: ""
  tls.key: ""
