apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      securityContext:
        sysctls:
        # Allows ICMP traffic (ping, traceroute) to resources behind cloudflared.
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
        - image: cloudflare/cloudflared:latest
          name: cloudflared
          command:
            # Configures tunnel run parameters
            - cloudflared
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - --no-autoupdate
            - --loglevel
            - debug
            - run
          # livenessProbe:
          #   httpGet:
          #     # Cloudflared has a /ready endpoint which returns 200 if and only if
          #     # it has an active connection to Cloudflare's network.
          #     path: /ready
          #     port: 2000
          #   failureThreshold: 1
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          volumeMounts:
          - name: tunnel-creds
            mountPath: /etc/cloudflared/creds
            readOnly: true
          - name: tunnel-cert
            mountPath: /etc/cloudflared
          - name: cloudflared-cm
            mountPath: /etc/cloudflared/config
            readOnly: true
      volumes:
      - name: tunnel-creds
        secret:
          secretName: tunnel-credentials-json
      - name: tunnel-cert
        secret:
          secretName: tunnel-cert-pem
      - name: cloudflared-cm
        configMap:
          name: cloudflared-cm
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-cm
data:
  config.yaml: |
    # Name of the tunnel you want to run

    tunnel: ldk8s
    #protocol: http2

    credentials-file: /etc/cloudflared/creds/credentials.json

    no-autoupdate: true

    ingress:
    - hostname: ld.edvsul.org
      service: http://linkding:9090

    # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
    # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
    # in the connection from cloudflared to your local service, not from the internet to cloudflared.
    - hostname: hello.example.com
      service: hello_world
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
