---
- name: Extend LVM Logical Volume
  hosts: server
  become: yes
  tasks:
    - name: Extend logical volume and resize filesystem
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 85G
        resizefs: yes

- name: Extend LVM Logical Volume
  hosts: agent
  become: yes
  tasks:
    - name: Extend logical volume and resize filesystem
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 95G
        resizefs: yes
