apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-apache-mpm
  namespace: nextcloud
data:
  mpm.conf: |
    StartServers          2
    MinSpareServers       2
    MaxSpareServers       4
    MaxRequestWorkers     10
    ServerLimit           10
    MaxConnectionsPerChild 500
