apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "9.1.4"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: nextcloud-creds
    valuesKey: username
    targetPath: nextcloud.username
  - kind: Secret
    name: nextcloud-creds
    valuesKey: password
    targetPath: nextcloud.password
  values:
    nextcloud:
      host: nextcloud.edvsul.org
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        capabilities: # Drops all Linux capabilities
          drop:
            - ALL
        seccompProfile: # Applies the container runtime's default secure computing mode profile
          type: RuntimeDefault
      mariaDbInitContainer:
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 33
          runAsGroup: 33
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
      podSecurityContext:
        fsGroup: 33
      configs:
        # Fixes the permissions issues when starting non root containers https://github.com/nextcloud/helm/issues/335#issuecomment-2318589992
        custom.config.php: |
          <?php
            $CONFIG = array(
              'check_data_directory_permissions' => false, # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/
              'maintenance_window_start' => 1, # Start maintenance window at 1 UTC time
              'preview_max_x' => 2048, # Change photos size limit to 2048x2048 to prevent OOMKills when generating previews for large photos
              'preview_max_y' => 2048,
            );
      extraInitContainers:
        # https://github.com/nextcloud/docker/issues/763#issuecomment-2752172569
        # create empty redis file for nextcloud entrypoint to override it
        - name: init-redis-session-ini
          image: busybox:1.38.0
          command: ['touch', '/usr/local/etc/php/conf.d/redis-session.ini']
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 33
            runAsGroup: 33
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 8Mi
            limits:
              memory: 16Mi
          volumeMounts:
            - name: nextcloud-redis-session-ini
              mountPath: "/usr/local/etc/php/conf.d"
      extraVolumes:
      - name: nextcloud-redis-session-ini
        emptyDir: {}
      # - name: apache-mpm-config
      #   configMap:
      #     name: nextcloud-apache-mpm
      extraVolumeMounts:
      - name: nextcloud-redis-session-ini
        mountPath: "/usr/local/etc/php/conf.d/redis-session.ini" # fix permission denied error
        subPath: redis-session.ini
      # - name: apache-mpm-config
      #   mountPath: /etc/apache2/mods-enabled/mpm_prefork.conf
      #   subPath: mpm.conf
    persistence:
      enabled: true
      storageClass: longhorn-k8s-cluster
      size: 40Gi
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 4Gi
    phpClientHttpsFix: # Fixes the nextcloud login issue
      enabled: true
    internalDatabase:
      enabled: false # turn off SQLite
    redis:
      enabled: true
      auth:
        enabled: false
      master:
        persistence:
          enabled: false
      replica:
        persistence:
          enabled: false 
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: longhorn-k8s-cluster
          size: 8Gi
      auth:
        existingSecret: db-creds # credentials for the mariadb container
    externalDatabase:
      existingSecret:
        enabled: true
        secretName: nextcloud-db-creds # credentials for the nextcloud application to connect to the mariadb database
