apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "8.9.0"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  valuesFrom:
  - kind: Secret
    name: nextcloud-creds
    valuesKey: username
    targetPath: nextcloud.username
  - kind: Secret
    name: nextcloud-creds
    valuesKey: password
    targetPath: nextcloud.password
  values:
    nextcloud:
      host: nextcloud.edvsul.org
      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        capabilities: # Drops all Linux capabilities
          drop:
            - ALL
        seccompProfile: # Applies the container runtime's default secure computing mode profile
          type: RuntimeDefault
      podSecurityContext:
        fsGroup: 33
      configs:
        # Fixes the permissions issues when starting non root containers https://github.com/nextcloud/helm/issues/335#issuecomment-2318589992
        custom.config.php: |
          <?php
            $CONFIG = array(
              'check_data_directory_permissions' => false, # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/
              'maintenance_window_start' => 1, # Start maintenance window at 1 UTC time
            );
    persistence:
      enabled: true
      storageClass: longhorn-k8s-cluster
      size: 15Gi
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 3Gi
    phpClientHttpsFix: # Fixes the nextcloud login issue
      enabled: true
    internalDatabase:
      enabled: false # turn off SQLite
    mariadb:
      enabled: true
      primary:
        persistence:
          enabled: true
          storageClass: longhorn-k8s-cluster
          size: 8Gi
      auth:
        existingSecret: db-creds # credentials for the mariadb container
    externalDatabase:
      existingSecret:
        enabled: true
        secretName: nextcloud-db-creds # credentials for the nextcloud application to connect to the mariadb database
