apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RRVoGbmiVdRYCUmqsSeWWw==,iv:v9zHguixWAdMCbucrjk6AxivGnj/Vw9AdaljHyvExX0=,tag:g4kiiWiKpbKF/6ZQ/ALE/w==,type:str]
    username: ENC[AES256_GCM,data:6MtE8/LwLBS/nCnP,iv:KSTN9VLsrdB0rKbfgc0E4IBsqdGgbxdB3VpQBeX0mc8=,tag:EuXIt5sfkFhdWScpvFKmtQ==,type:str]
kind: Secret
metadata:
    name: nextcloud-creds
    namespace: nextcloud
type: Opaque
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrczFSY01wM3ZVQVNUM2ZI
            dmVYRGQxcWFxZWp5WWlnYkVBOWxMc1h1SmlJCktTMHJZVDk0VzBMdXMybWFrbVU4
            TjlCdE1WbWl2d2Fld0FnLzVRdEs5WHMKLS0tIHFEVmtYZ1Bkd2crdmxnalUrVFN0
            Y0x1bEx4SEhwMGI3SUQ2MS9KQWZCejAKuvVnXvQYsijMTX46NCWboUe+wI4CbaG1
            9L6mW+qEsnL452t7/PfZYB38IEdhxCYRnOMNX+4Upq2W8c3UNebAsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:34:24Z"
    mac: ENC[AES256_GCM,data:nQTT9/c7d2SdAXH/WRsbwcP7MEZOOfJt7NizK5DG5Qyk+MjNRQMuxD3IaVPJtU56qyuOlYQCC9cC6v8gEFc3PSc6meDUmOvu52EkUiRmVtIz7bzuEYsA8sSKASdNXmxF9MXtoqoZHmblOXnhhJWJcQnq6jy4ELJtlSHDrv0w9FQ=,iv:MFLCjHAHg+EQrr57NMsG99/slQXYY5gy1TKAKiuHQMI=,tag:enmqb4QLPTSwXgpkWuzUoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
