apiVersion: v1
data:
    password: ENC[AES256_GCM,data:RRVoGbmiVdRYCUmqsSeWWw==,iv:v9zHguixWAdMCbucrjk6AxivGnj/Vw9AdaljHyvExX0=,tag:g4kiiWiKpbKF/6ZQ/ALE/w==,type:str]
    username: ENC[AES256_GCM,data:6MtE8/LwLBS/nCnP,iv:KSTN9VLsrdB0rKbfgc0E4IBsqdGgbxdB3VpQBeX0mc8=,tag:EuXIt5sfkFhdWScpvFKmtQ==,type:str]
kind: Secret
metadata:
    name: nextcloud-creds
type: Opaque
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrczFSY01wM3ZVQVNUM2ZI
            dmVYRGQxcWFxZWp5WWlnYkVBOWxMc1h1SmlJCktTMHJZVDk0VzBMdXMybWFrbVU4
            TjlCdE1WbWl2d2Fld0FnLzVRdEs5WHMKLS0tIHFEVmtYZ1Bkd2crdmxnalUrVFN0
            Y0x1bEx4SEhwMGI3SUQ2MS9KQWZCejAKuvVnXvQYsijMTX46NCWboUe+wI4CbaG1
            9L6mW+qEsnL452t7/PfZYB38IEdhxCYRnOMNX+4Upq2W8c3UNebAsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T13:34:24Z"
    mac: ENC[AES256_GCM,data:nQTT9/c7d2SdAXH/WRsbwcP7MEZOOfJt7NizK5DG5Qyk+MjNRQMuxD3IaVPJtU56qyuOlYQCC9cC6v8gEFc3PSc6meDUmOvu52EkUiRmVtIz7bzuEYsA8sSKASdNXmxF9MXtoqoZHmblOXnhhJWJcQnq6jy4ELJtlSHDrv0w9FQ=,iv:MFLCjHAHg+EQrr57NMsG99/slQXYY5gy1TKAKiuHQMI=,tag:enmqb4QLPTSwXgpkWuzUoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    mariadb-password: ENC[AES256_GCM,data:+Ye3PG9SFf5JFfpnOGBhuA==,iv:Vg4qB6nK5l0QnD5rODMs4UHbxUVdwivf2CY233qRdhY=,tag:+7hEQkWO5kUIus2PmpCPzg==,type:str]
    mariadb-replication-password: ENC[AES256_GCM,data:9fm7aiupPXpB8gmbFFQUqw==,iv:nW+WN3d64W3yTlRIN4qk9LFoyIuUseYcUmb1hFW32pk=,tag:FEeNzxswriAxqvV8gbE/pQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:ZyUZyCXVuYqPB8ZCd2Lgvw==,iv:ZZKVYWukxnA6AvGHzP7lPw7zgDa4y1rQEFQrQDURnYc=,tag:qOfzVJemTAP1HLHVaKg0yw==,type:str]
kind: Secret
metadata:
    name: db-creds
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ3l2WDBMN1lRUzJ4V2k1
            N2YyeTZvVU5QSGk5WnVjRWk3ZXJpZlVtTm5VClNZRzY5UUMzcS9hZDZQemh1dlVH
            bFpUc2hrWjkxN3k4OFBUZnJrNVJZMWMKLS0tIEhZYWFDMnVqS3RrSVRCTGZUamJI
            YnJVRGc2NkhxbmdjejZoZE5hVlB6WjAKPzv8BDHY2+LMuuz1j8HYNeAgiCa17APg
            MZ6TpSL8mo1kimEm4D4yZ8EbqZL5Blb55K0J576XfQTmrKh+OLc6RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T19:00:59Z"
    mac: ENC[AES256_GCM,data:5Ct5xquQTsChg8UFHL2mFlQ+e5MW9GRqLyI3l3zKoCxhnx8ooCeXzqlmJybFLo3dZIRC0vUXe+b/GK/nVXdcZm/TOIZF9gnQO686E01FhtaEUR+1dt7Fey4EEBfM5LJZfl0XX9QEHKO63E/SfY+r+Q+Squ6BAy5yLFpk8NYdyDM=,iv:iAe1nzQkPUdg194A5smnJ5q+3i7pX+9DVDonCoq7FuI=,tag:rTajew6MSeDzOSDL5oXcQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    db-password: ENC[AES256_GCM,data:K0BuIXfLDXPbSZOa6Qz2Lw==,iv:qqMCIK+q2pHkQ5H5GBXbhjYRD2ZoKbgEHrUx+C6pwnc=,tag:86W3z7qml1ZksnP6xPVj0Q==,type:str]
    db-username: ENC[AES256_GCM,data:HsA0oM7ZuAgxrC1h,iv:c2zJoF/Y0v9tq9ehbnuTddklNYuaKQUu1ofIdh6P4k0=,tag:Pe/yTHIsckRqepVIFh7Fig==,type:str]
kind: Secret
metadata:
    name: nextcloud-db-creds
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeXVkMXNCQzFmMks4b05w
            WWNGUkI3SVYwVXE0bG91MGtHblVCMVY0aXpFCjV0Qmt6Mk1iNDBmOU9rckdrdzFL
            cDB5V3BJTnJTdTJhUzZDeXRqdG8wSWMKLS0tIE5ObUU3dlliUWN3dVpBcXBoOUZu
            KzdjY1paSXpmYUlRWTVBY2RCUlFSUlEKxoh3rJkFgQ5Zox/q00EVgWilHWMXlxSX
            ddTQs+4fnk4SLk7LCJ/YHZV2/3W4XUvPi7aEoGG3LectbRBk3S3CWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-11T19:32:34Z"
    mac: ENC[AES256_GCM,data:ihSh4P9f07RvQSuOT5orZmdbI1UwpPh5RYwD6oLuCrC0vk2FkznxEY46tgYS89B1XDT4U60qlI5hpZPEs4/fIFBAg7zfvKj+aaf269lb7Mm7pZ2Q6tTerJEXXPGyOcOwvp2jT/ZoOPlM1U3uMOa3BAXN1BJ0EWlGYVT8VYfnlf0=,iv:ohF4oI/EQi8sH1WWm7lnL4yfZFj1WLDmBbPo0F1Ld9g=,tag:w0WPwzJW3p4NYrBY0qQoOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
