apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:FpEsqHb+HUPd+/3EZQmswqKDZvuqTMs7+wrShUEyYJ+D24n2nWTylu6U+X4PEsyS09/AJdan4izmJJKRA3vFN6DiLuJ77GpYUFUT7I3ZeBc7Fox0S1wAIGU0brkj64uhr9MWvji1T6sg9IMBSp9CU1bKiyvLs8P1tQUtxI8aY1KmMILrZv0m6vOea9J9xVCz4tcctzoIFqHhOKip2v0RCOh3aN/YgBJh0Qzf/TpT32VG4s9+moe4lcaJB6JBDQDHdZ4V+H4dnXZQb8G91rxNwues0kYxwhuQAsTONXubWmqWc0huOU0NVgrDzmE=,iv:4VKmqmqXRxjvvQe12z5Gu6bCxzZ/+vACCVa2FOGGtI4=,tag:AKlrs6RxvCz1oeOf/yi34A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUDFTRSt5b1d5dXpGY0dR
            VlVaM09PZ0VEWTlmKzN0eWdiSi9IejJPaEMwCnpURTVhNURoWnc3ZHFlOWl1Uy93
            Q1RvNlc2eUNtNllHVnRVTUhjNWxBNUUKLS0tIGlPUTFRZXgzeTdRN205MzR3TlJN
            V3k3WVRKajlrT2NrRjh4eVplMWxPUk0KEwdGppMY/HLN5dlz0hYO1D14xCDauxpD
            wnQHhwGKBzrcx26Y/sFjlXZYktbevNN8+rzPDGZ8kOLZT5+BPvJTfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T18:45:09Z"
    mac: ENC[AES256_GCM,data:8t6XAd8fu1LZ9I8UttDPQK43lVen4UKbfIapq50LSORL/w9TUsHWsOgGkWsH4i9b0W7VnnOefOIgUqb2AECcKl4MsFbahc6710uiP5eOqfrC9QD4sWrMtQ+ZMHC1AuAJeQf0brYVgHgGoc9mLu/NqGG0r00oyjRduAe9DiQJn/Y=,iv:EZmJVvDrxpC4CN3ZEkMkxLtHynD/B5TubETfkiZJ54g=,tag:JtYR7KVS7ibckjRXTY2Z6w==,type:str]
    version: 3.13.2
