---
- name: Extend LVM Logical Volume
  hosts: master
  become: yes
  tasks:
    - name: Extend logical volume and resize filesystem
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 65G
        resizefs: yes

- name: Extend LVM Logical Volume
  hosts: slave
  become: yes
  tasks:
    - name: Extend logical volume and resize filesystem
      community.general.lvol:
        vg: ubuntu-vg
        lv: ubuntu-lv
        size: 95G
        resizefs: yes
