apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firefly-iii
resources:
  - namespace.yaml
  - repository.yaml
  - secrets.yaml
  - tls-secret.yaml
  - network-policy.yaml
  - statefulset.yaml
  - service.yaml
  - release.yaml
