apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-app-key-value
    namespace: firefly-iii
stringData:
    appKey: ENC[AES256_GCM,data:WRfD1g/wS2L+0VOuTs08eNRNr+oHH5CmJ4Iw62VK6zY=,iv:4BWYjcOGl0DVkJhL7CrvMQB0QuudifPauU+zACfMSrw=,tag:P5FA1P8HAe6Ot6ciYOEK0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMno1K2pjc2RXOCtxTUVk
            TE5xZ3VvWWttWTRWbFp0cDBUbXBpL085N0FzCmZvMzRBR2R5bThLU2VJdURVS1lv
            cGtqQ3FuN2dtSXNrbGhlcWFsTlBFZ28KLS0tIGtZMGkraENjRkptek55SnpJUk9R
            RFZOQXg0Y0g2bmhvRkx3REltM0M1MGMKRTe9bQhES6ddv7MQWry+Oc9/IhmufVaw
            CLFkoURPonx0wIIdpxrrKJh8OEae7pABmN+NnheeoqH/fzc4xR8nsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:59:19Z"
    mac: ENC[AES256_GCM,data:/ku58SXU66qK2qwfQt4qTa1MtNeYFhaq1E0b3vZF7i8Pa2ucgyu4F6BUWje27thNlsQg9FwF8fS5MU1ZuyAmNKqh4ckFZVTlTInCGni+RUppyz+UhU5qxzbRd9sns0MJ/vTGSLtOUlMcjUgUsNzm+xWAAGNK4p2ae/h3ipjr3Ok=,iv:/+9lUb/rdSSqn7XAbx+F97MQSjyYBB/oGnBIParkZO4=,tag:ENNV0b1puUmdkmH2QOnVAA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-credentials
    namespace: firefly-iii
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:g7gLO0SgJNGUqZQ7VeMq7g0N7i0IZ7SGrRWmyA==,iv:EswTLPvZbDQoW/zTq7xcyXvDMJoC8Oc2LeHiwAfY88E=,tag:Ym47Z6oT7rZmOypGNWmJpQ==,type:str]
    SITE_OWNER: ENC[AES256_GCM,data:hQDqAlkjLbJFUiIbArrpsljwgRXkOOQLd0U=,iv:qJ0wWBoWqZcPaSEmsJ19MagcPEpaTDdBEgJI7Csy59E=,tag:GRNZjF5Ezr11h+DFC8bKKw==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:a42m,iv:xaPi3oagnyUqD7sYeo/1Nh/Sc7udPXit5xbOZQU1GM4=,tag:BnIRbeKgSXnd9WsHytolfA==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:LPgX4XosFgqLn7u9rtv43CHc,iv:cDXlp50Ckyv0nua6AwGbkX21Dalnvgs33S2k8SVW5qo=,tag:TXiYADdzprsIJzxJlLaKuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMno1K2pjc2RXOCtxTUVk
            TE5xZ3VvWWttWTRWbFp0cDBUbXBpL085N0FzCmZvMzRBR2R5bThLU2VJdURVS1lv
            cGtqQ3FuN2dtSXNrbGhlcWFsTlBFZ28KLS0tIGtZMGkraENjRkptek55SnpJUk9R
            RFZOQXg0Y0g2bmhvRkx3REltM0M1MGMKRTe9bQhES6ddv7MQWry+Oc9/IhmufVaw
            CLFkoURPonx0wIIdpxrrKJh8OEae7pABmN+NnheeoqH/fzc4xR8nsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:59:19Z"
    mac: ENC[AES256_GCM,data:/ku58SXU66qK2qwfQt4qTa1MtNeYFhaq1E0b3vZF7i8Pa2ucgyu4F6BUWje27thNlsQg9FwF8fS5MU1ZuyAmNKqh4ckFZVTlTInCGni+RUppyz+UhU5qxzbRd9sns0MJ/vTGSLtOUlMcjUgUsNzm+xWAAGNK4p2ae/h3ipjr3Ok=,iv:/+9lUb/rdSSqn7XAbx+F97MQSjyYBB/oGnBIParkZO4=,tag:ENNV0b1puUmdkmH2QOnVAA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-db-config
    namespace: firefly-iii
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:HU5MGPfomQ==,iv:es0ZdcvcCDDdxR0mP6PcfiaT7D4Fn3MhkFe8yPTnIms=,tag:mD+cBoVSiAJp53iyODdu6A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:dsZ8dEPmJETfgYXU/zkmK8Id6nw9ipJxrJoLeQ==,iv:Tcu4XblBoLFSGTGdHVmCUp8Wk0ScxuRPX7beVji9qHo=,tag:uaTyljQwwCNTS4aijQT1Iw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:pyaHT+nCqw==,iv:4ad05l5aU164aV2kkWE+aOyZhwP36BHx+GfvqV0Sa5c=,tag:HHWrAirNGVNrCrsk2Gc6+Q==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:6strxUBLBtP6aU/rOCKkHUEsbh850rtyGeHWXQ==,iv:dIpcSkCJP5sJ0yj6JW2LJ/AOE8PZfPgHlZdeIhLAgT8=,tag:9xciOM/sM08awQrsRN+Esw==,type:str]
    DBHOST: ENC[AES256_GCM,data:fdwAlEu7Wb3kZO16iP52hkzVrCjy/w==,iv:ysY7evnekl53xTrALLagqdYzvtofs50vyRJlu6axNN8=,tag:LphlCBV1Ov054YQ30N92Sw==,type:str]
    DBPORT: ENC[AES256_GCM,data:9lGFcw==,iv:aGgXpceJRVwmGcFmlJ7C3mkS6cvHqC87M3RiSM9cnqw=,tag:P8Gu9OFGvqGJlN6HvyqtGg==,type:str]
    DBNAME: ENC[AES256_GCM,data:z/e5ENcGfQ==,iv:fcMi/S/uujk+1+rkBRJwM8mytoK4+AKfxZXBOs4oGKc=,tag:KbwQqQOaYWgDiREetVCvDQ==,type:str]
    DBUSER: ENC[AES256_GCM,data:B9eShkfcCQ==,iv:61tiDCEzhm/qeM9OEn/mL+3Vn/9qwg0n1mrKSSuMwKo=,tag:/TXxmM8f++tbJQ8GNE5Sqg==,type:str]
    TZ: ENC[AES256_GCM,data:DeZT5O9bnv+4X3168Oc+kWE=,iv:Z2/4lo2mbeWf9B++sD5wbjcgVJCzFrOc/7UF9z0f6tM=,tag:rt5qZduLR/qVYi/1vy1lDQ==,type:str]
    BACKUP_ENABLED: ENC[AES256_GCM,data:FZCzhA==,iv:mUGrVekFPcaPcKRgmG5cHEBeHh3iqDYWPrG7oVB1FBg=,tag:ZKPa9n/SXCiJyzMBqv2gmQ==,type:str]
    RESTORE_ENABLED: ENC[AES256_GCM,data:MWM9EcE=,iv:9CLu6GPz+014ZjpZI75NG8fCSWJwLBz/hiQSuBGxfig=,tag:opTz6nPOKXm9vteO8Ej/Yg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMno1K2pjc2RXOCtxTUVk
            TE5xZ3VvWWttWTRWbFp0cDBUbXBpL085N0FzCmZvMzRBR2R5bThLU2VJdURVS1lv
            cGtqQ3FuN2dtSXNrbGhlcWFsTlBFZ28KLS0tIGtZMGkraENjRkptek55SnpJUk9R
            RFZOQXg0Y0g2bmhvRkx3REltM0M1MGMKRTe9bQhES6ddv7MQWry+Oc9/IhmufVaw
            CLFkoURPonx0wIIdpxrrKJh8OEae7pABmN+NnheeoqH/fzc4xR8nsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:59:19Z"
    mac: ENC[AES256_GCM,data:/ku58SXU66qK2qwfQt4qTa1MtNeYFhaq1E0b3vZF7i8Pa2ucgyu4F6BUWje27thNlsQg9FwF8fS5MU1ZuyAmNKqh4ckFZVTlTInCGni+RUppyz+UhU5qxzbRd9sns0MJ/vTGSLtOUlMcjUgUsNzm+xWAAGNK4p2ae/h3ipjr3Ok=,iv:/+9lUb/rdSSqn7XAbx+F97MQSjyYBB/oGnBIParkZO4=,tag:ENNV0b1puUmdkmH2QOnVAA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-importer-config
    namespace: firefly-iii
stringData:
    ENABLE_BANKING_APP_ID: ENC[AES256_GCM,data:aLySLo09NOWRbzLtj2oA9aAT4XX2/roaUGzqic0whP+mLvB7,iv:HzWVsZf+4E62EfGKHOo8dKHgfn1nK7IOCsyFSXz2tkc=,tag:g+4GCJWbg99Cg+IKyHJMuQ==,type:str]
    ENABLE_BANKING_PRIVATE_KEY: ENC[AES256_GCM,data:NTs/9NQeAOU7CiZ88u7/33qIpWJfPO6mqIFKlKvZq/9rnGvgXTA05PCG4M7cG8E3NrO/sHvuMvWbeYLkB/BvUeHq1Pp6nczMg7iudMcYkrZoe7ye9rZ4x1lwaWf6OJ4QOPmDZyXoHfvMglIljhngXjbjIYEBFVeffT4whEXfIqhtlHrPFRIrEiNP8tpz+xRJYfGXvIKy5QolbZge99iNs1ntk8lC4wMdoa4THn0EtzYijfhseo4d0mXIn+WoFwkeZX5ZddiXjLs8e2Ya1vi7mTIcDq4C2cCgiWpCWVL94+CYjT6KZ/Sub1hCHRLeRpZ5x3ASLraEbUf7HIw64fcNR3LCxxv7KYLEY9UVJ8vblhDB0qU/bJbqYMzyU4vEsmOZwbaEqoKyxq//gdOMrzEeC/3urwPGlKkJ8Ayb8o2oDT+PI0aIX5TqJNm9H4GtWb3/m+n6wx9mlq05VaCnepoFUe2UcMg5tWg5ls7eN1nraPOFxAHmQ3FLY74g/xO5ia8TyI4NL6oTSaxYT2B2bFdfFIjZf99peDUgBHx4ma1XvKcUp/upnCzC9y07vxPun0F790Akul8QA2YAXq/llS+UOqJQ4JugdpJWFzkvviOY4ECPbTeS75zOFiJMkUBnosprH5hIpQiHndf/U8ou4v0ecIulHjl6/A4jF2HqezkeW/BN3zVFa0WVPQCnYG9GnsSoggC0xo4BDmpclPZEyp7uLocv0heMlNRVs38mkjM0+q2nXd5c5dk6lnOTSHrCu3PCR2Nbnib1bU5Y9QywtfKd0lF64eww4RX8JlLPNINxsAgL46PWQUcl9h8k54YREC07X01GVRtznzFyy4gP/8nxMt6aQtDOaM1PAEVa74vY5j/xQisGAkeJXVTsG4uTeT3QkVaU7lNIOi9igo732doxbaO9KG3fVI3KdsQq9eRHLxEqZ8nvmKAvQnazhlxtVosRYIF6fdah5oRismGGrwGVA/OVhbpLwKJbWU/m/K1ILJAJh2t+0/YtY5cIIF4dria+K+oqfSSQEYsVsuszWCPkelYtFWxDNmyhfPcXg7aItrZI7prPeDjrwgY/1kuy5Y3L7qpdmOJzbL/UiqCmJB3JDompmoJoBIUTKd2nzN42vAGCCyiAvUiGwbDctfO8xsZjM9N6UGntjCcJKcY36mymhee6q9PK3dgu57fB2+HxENyLMnkLq95AEeEKJIEdI8JwXZmKFHa/Q+LFMwqFv1pruAVL/mwwN/yI+oiDUmmlIf41RNwzYJJ98pBBfLNatRcR+yShexWZAqmig0hJoWW/KwI4umPFr5xuVBErQiM9gEKqU0F4B1C+kRmssntAXR9U6ewYFBZz35tTMvzR1n8nHIS0gyqhDlbHFQLVO4XdmR2VdkQ+ymu/uxCCBvzLpu4cErciJo1Mq5FLI5qcZSskeNoTjSQSzV92SZ0L/qvl+dcsZGxtQJ96k9ri+IGNAmUSmO4N0+onO/pnCVUWVXoOThuBtEL8BWjl5GMuNJM1rBId8QDnAHji/7GgeKHsmoqslsNOqlUwjfOVzjSvCKVnyRUadVtzNWXoq2YB5K2MXCVr7APQy0gnZG4O+ywjL1loB+lVH8cuKjS8PjRvmrH4pq77EIlhrGx733ejhzWdazCVLwc4s9wNa6jvgIRc3NcmsFygQ2aeMa0bg0MGrlm0fC/mi+U19mu1vutp0UZhwJlIqeNQaSnyiVX9fU872FMSCWJlkAJ+XRQYiATby8nQ4269WnNR5W7t/NccFqb4M+FxVEhcqzhPrRIKIdl8Mz4AnjNSlr5sDfzSPNJz24MJD6xND8l7vXDgTh75omuXj83fwBk6zaVhGJOXtFBKa+XxEkVGTPPgQF1ZOYHmvIYblE3rnJwnf5BClz+idTchw8k7ngM2KjzfFaeJEYhaXvbd8bBmq210eF9Sy41Zi6uBG7avHS1M5wOXHU9QN0+JY58jJSvv8t697mPv90s5+S7kIIItU4GvZ72xTnc8XGKDcMzKcdBvFIDvdx7Wbsm6Ngi70/4WYyKqVGAdh2LpCK1ogEB35Jt7AUbfDH+HL6+buEiEn/zcv0v484gTF9p8BvjlYuxouQrtWDsdYV+A4UEnMIo8jfieHUN5gk20la/MFxYykn5ta0yvz2yhVi7XqveH8DZVlkKhCwHEwLN7jMaYTWo2m2n54n+uk36f6nbKTFSyvLLUcnqQs1JwuwKMeBtkjP5Nn7sGysLlMyxnK5pH+f9ySFSdNz+z0i5isglS2VOCXIkayEiH4Z11xAeI+z3ZhJsNvTwhRBxakzd5Fh7LDrUAyactYtLGYg4npIoy3/lCIVxSe90EUQHiC3PQHxeShhXfuZlZPd9S3ZzqwCD/W+Vxe88DeoZCgcRfNDA2+9RgO2+V7MuY2uCoVG0XVbznVsMgw78r7Nukjh6jiC34w43XMULu7YYFUjha3PqmPDzZUxflIx3nXcNUs/RVjsBp/9V/SaO9iV84iGgsNrhpgMBQejeZK5neNTJx88t0nOOzj9opiHdJphd9txVpTEUn3sjRCX+KDEfn903COwlMB4FSJk8gesy7gsCcbbgK8vYdevellHpbqOCnxld1nartUCQlg9s0A32JwAeq/l2lqn9eFj0rBwdMePi+qevG4Jj7nzZ0nqBlyoFWrD7aV3mEJzbhykelen7XHzbjIAbTMALTRbFTpK9nNgy6ZiqfbvBhan8f5Bl5b9gPQWnBt6CdFk9WgdY1BrNEOUXxXPfG32pa0PbzmsUzW41OxOuSbCnEZMb9/NmXEoSpQzPAtoTGn8mq/MoW8jWE1HaxguHDYmitGKM2vNNMT3PRjiF4MAFpFFONqTYPJPN0oSmGCRWB+v/44ie6n/rgAL963DlRkorsvfDxZ/G+Q7QGdD2owonr4DF3fGNRyYPk/EtgvMnVf150i37hZhVioka148mvCiPHQJcbMaYRU113ZWWazr+M2+Jd+pv9V2qTSoI2YMPQjb5hIkbzHe2wzQbRZnytV1WqLHNIzbq/w9mpNVguVu757EHMxcu3QnCv6jM6KTzb1x5bprof65gPZjks/nyK5a8YBWAxH8wQg9yR7a699sSW7NDjdkZBNOBv4u1KUzYGsVMS5z5L6fFRxC56rHD2qNfisPvu004J8Fv+xc5Zh6aLijpNDq6gE5OqQBYZwoSZQd7AAlu4eIzjUAi9ELZ1XkVizKf4akqRLbg3FB/8ez1rvMkEWrB7KTPwTpeUpwg1Z+yPScjyxNGLZT72Jw1PEolr8fpcoJeLc+1kcLxCiB12afmWNiQAn7uZfzSAFso+/syPsF+P5CJ1z2ZrVX8WDipmCfwkvqqxCH1NYtU7Ki5kaAuLzERHvav36j54Ia2mlCq23nTHw0lJuaxsnytT1ejugCnavpNKh9gpUXmMo+8LQ56Z7Kd+g9s18M+x1ylstDz5UOHNyqsLechS7tCGvw+AZMsipVBpRWFHzLUFTIRiMji6ZMN7Y78aS7cAADCkRw3xOj/S1poYmKcpRYyl2ZvfoLU6WkCM/RXz5KQWd50spBW0Ag3MzjDq7bjSoIbPZzPUFuETOLqq2xaHiy/eVC0+Gj77JK7pkmR9sOPJE9QdKZ5ZOLqp9BiCfnid+UwRKQHS6brGoHkBV6QdWsSy2gLXXgi5ARd1mt+c69oeWk0+/4Uj/VgBGq2cnR+bSDAw1tT20Z8vy8boD/9bWAcRT9P9bD131QebPbscEx5fGiVDNZjLJJ6mVswsbBzGouZ1+IyyKPNmxiVgJIktQYL3dKjBPpI0j4GAKz4f4c8pYQX8VbJQeG9cs26Z/wdsC8iZOiPDOorxWSL8q3LP326TLAzwxcjyg7PoTTtDJeMR11jtoC662gRj2rbA9ww93HXHV3leiK1YP821Shxgp65871AYwB6ptrnMiknzm6RReh45uMFVoxA0JYEy/Ov4/A7/oQbUnxxs1x2txfKi77pXUh8TbcOb2g02Eg9Lms7GqpDQTE/Bad6GmGkzyNKkhO9ogf157TSU3xR4x1ROUtlH93sBnZ6DnJ+fdw/Z491F78amPh4WQGD+Wh2IAaRWE7DI0biLZ/t+7J5uJ2h572IYPHCnZkoOXGpOAJnY+lJ3wyLmu8LyX44y7f9x98vN5XmgD1hQBslOwsob3e8fzd2mD0wgI8btMjIBFi+X8YnJCE88GVyfOBabA5+PkufiKbHvgJxY51BNoeYRAMZB48mF,iv:1adbQpP47yoz+ygmI26PJ7Txn+fLdhTXiNIG5DyUba8=,tag:95RnGjAfynNI/3fktsIpGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMno1K2pjc2RXOCtxTUVk
            TE5xZ3VvWWttWTRWbFp0cDBUbXBpL085N0FzCmZvMzRBR2R5bThLU2VJdURVS1lv
            cGtqQ3FuN2dtSXNrbGhlcWFsTlBFZ28KLS0tIGtZMGkraENjRkptek55SnpJUk9R
            RFZOQXg0Y0g2bmhvRkx3REltM0M1MGMKRTe9bQhES6ddv7MQWry+Oc9/IhmufVaw
            CLFkoURPonx0wIIdpxrrKJh8OEae7pABmN+NnheeoqH/fzc4xR8nsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:59:19Z"
    mac: ENC[AES256_GCM,data:/ku58SXU66qK2qwfQt4qTa1MtNeYFhaq1E0b3vZF7i8Pa2ucgyu4F6BUWje27thNlsQg9FwF8fS5MU1ZuyAmNKqh4ckFZVTlTInCGni+RUppyz+UhU5qxzbRd9sns0MJ/vTGSLtOUlMcjUgUsNzm+xWAAGNK4p2ae/h3ipjr3Ok=,iv:/+9lUb/rdSSqn7XAbx+F97MQSjyYBB/oGnBIParkZO4=,tag:ENNV0b1puUmdkmH2QOnVAA==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-importer-auth
    namespace: firefly-iii
stringData:
    accessToken: ENC[AES256_GCM,data:QeQkJaOnAEmfZsh+W0yYbMhf2GWtqn/1i022isG+dj3C1c7Dz/3xZdYPYPK8huLVj8WawVTYdV2MPN3vNDWFcG5ohzbAXACJBv+K+A6xy1JIsRCJ2hiIu9jDz80w5L/kSY8CPU/1EsxWm+lJQP9hIsOA+QCcs++INaknVXL55aRwfMEmup61dyZSIC8P3Q7ZF7jJ648n/BQAnrDHix4cRCIcSczmW7kbqn5hHLxlaz4WLJarmqM5zBZvqjc38BjT1GnOqUIklNI+GdeWRpuzFA7HsNB+2pQp6VZOdX5TSLw+GBqAJYH7I4tf4EMrJWlc9IE4I3MGfRMWvC6dC/rTihJfByRTsncIayKiSpmL0Y90vY/6npDiUCHWQz3h9FL3Uk2ODc1ES2Ad2eo9xdrn8tLIgVh8pgJfLaPMK6kJB67u9uDvQpOduFwoR7SSBH/xoWhXrfXmL34rry/wkg3zkj6/sFxoS+LRKCqhN3E59WEpquRaq3TVhX049hSKXVi2Ltoq/OYUL3F6IOT35G+mUxP+A5Xru2HREKP3mS4BBKFYEnVNM6iFqRXhJaqInVKA/spKk1oEMDe9G1y0x/9QST4Rt0IjQFxyTyu+BqMlVd0h8vIdALBaZwqgJWrl+4EgW8b2HK8mUHEvZSah/NpwzCng44wBuPoNrA0dwzv7wt/27vrCVZVBpEevSVOuBjV+cLguFuSGWa4X+3H1cmxL5ax5NkAOCztge/UzlWXKwG+rFsWz5Iigb9JH0SuqjbHXD5eXYb2hsE2Tj6SzPBEMPVNGiHMO46+JSnplOa6pq6nN4Wlf3/uZu7YUOcvmw0VBQUiypB0FLHDrm1n0dBCCsQsNpxyBinZfb9WxGmNN2DpYbGxA3DDd8aDhHHRjPna/Vvrjq8amT54pUH36sY1nR2LykvTsmlOdXXIYwq+jGNUIbsw9rFIZuRgewkwPlewUh5eh2P/JRFvSg7vxZ31Z2aCUqRZTBesPsfxLOzqTDyuf6ljYixjbhPe+EaJN2a+O+GkCMBVl0iaqXYBeGTsIjGX/WrmGAF1bby7gwsAGN2qf141qfP7Uom4F4hRoyO5I/78hv3ko/5TGbfhsUhucijtMtsKuQ1dBleEtstV9YES/gEhZ2Zfuv6LSvFODhsn7mLlTx/ylC4RcHrFKwnx6p0iw7JIgqV38DFPcHHOT4owReDn6ym9dt1PmZbhoATel1C9msJ1dDYXMin2ZM2acb6aPnqSqnJ9Yw9sdrsU/wTarn4HmR0RXLNRik7ncgU1pci1ShovKrBNa24GUJND2YkOyGdAMHagexXej5ZEH2ZvWNFd6Gnz5a6qlYSLp7MZuDCM+EwYIrYjlMSRyvEI7ooc=,iv:HLk6gERPCg1SRfelRgIBQ9mYkJbh/ZnIikpSFSaNEyI=,tag:HpK3TlkJ5UcLd91tqjsh+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMno1K2pjc2RXOCtxTUVk
            TE5xZ3VvWWttWTRWbFp0cDBUbXBpL085N0FzCmZvMzRBR2R5bThLU2VJdURVS1lv
            cGtqQ3FuN2dtSXNrbGhlcWFsTlBFZ28KLS0tIGtZMGkraENjRkptek55SnpJUk9R
            RFZOQXg0Y0g2bmhvRkx3REltM0M1MGMKRTe9bQhES6ddv7MQWry+Oc9/IhmufVaw
            CLFkoURPonx0wIIdpxrrKJh8OEae7pABmN+NnheeoqH/fzc4xR8nsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-18T12:59:19Z"
    mac: ENC[AES256_GCM,data:/ku58SXU66qK2qwfQt4qTa1MtNeYFhaq1E0b3vZF7i8Pa2ucgyu4F6BUWje27thNlsQg9FwF8fS5MU1ZuyAmNKqh4ckFZVTlTInCGni+RUppyz+UhU5qxzbRd9sns0MJ/vTGSLtOUlMcjUgUsNzm+xWAAGNK4p2ae/h3ipjr3Ok=,iv:/+9lUb/rdSSqn7XAbx+F97MQSjyYBB/oGnBIParkZO4=,tag:ENNV0b1puUmdkmH2QOnVAA==,type:str]
    version: 3.13.2
