apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-app-key-value
    namespace: firefly-iii
stringData:
    appKey: ENC[AES256_GCM,data:Q3l/KFnTMwJUjBF7E1LVG/fBV7bg8Tpoj0zzyn1NRN8=,iv:mRAhH+5c/k7cPxT7O+f4flb4k7qibPgiaP7nBuuoPNY=,tag:FpnPP9DzgxvuMVFjuAe/+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyajIzYitrdVcvWTZFZE84
            WWh2Ymt5bWdlVHFpRzc5QllMR2ljd2h5eFIwCmpEeUlzcGhJNmdDR1pRaWw1VTB0
            MzcrVUl4QWRraFZNY1RJSUlVUFBOT2sKLS0tIEExYVJ3R2dEdm5wZVN1UUhVVVVQ
            NmorQWs1RlRPb1RuQ1VnOVc2dkFiVFEKoyBbRUX0I75g9ujseppL6090DyirBXbC
            G8apMnBWlnMk32QssBVqLNYb8FBCaITR++V7HWIH81JVYfwzAoQqaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T05:16:25Z"
    mac: ENC[AES256_GCM,data:PXhplAp4Tz3OwjEGeVxnaAO0lO/UBbK3KwJAAxP/M/5V9WV9tjwB2GrawZa/K2B9Il6L3OCaUwyB4kT8u4QNyS77TQmoA+yVNAFnb251YduCp8vdeoXnM6KcK6KLmCn+vIj/MSVuDBPPWyNVVhfk/8L2UAfMOT0HoFCss2vXPsk=,iv:8ULASi4A3+rNNzzPoXKdd308VIFppaPK+YYOW0+iv5E=,tag:VeeYGvOGriL53dtviE+PVQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-credentials
    namespace: firefly-iii
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:W18PMuHVSAbVP/8VUz2p6YgJM/8pnnC9X0/Xkg==,iv:d/RydZt+MXRQk9UAcDlAEPiunOlaVknnRwFF416Y++s=,tag:UdAmu4itixaLzCOWaesbnA==,type:str]
    SITE_OWNER: ENC[AES256_GCM,data:rchoPvSnGMEyEjBucx3ggJoehs6FzlrTrSw=,iv:Ip0AbgLYIk8zCLcwO1NePVl7s3i7umQFri+ddOIVdaE=,tag:DkZeSHsW/vX55LClwQvzWA==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:0AIb,iv:eM+Sgk9oksp8KewRDO/TaS2nLnCoP0b5X+uQvcGcj6o=,tag:Cm26qQuMyar0KQy0chAljw==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:ATJBmwR+sC6Xh/GLgRzl+TYK,iv:TULRIKT0OhC+iNGxdfzFktS6ECaAaPuvRWy9ozjdrtw=,tag:f384Q8CHMEIzndhmz1Ik0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyajIzYitrdVcvWTZFZE84
            WWh2Ymt5bWdlVHFpRzc5QllMR2ljd2h5eFIwCmpEeUlzcGhJNmdDR1pRaWw1VTB0
            MzcrVUl4QWRraFZNY1RJSUlVUFBOT2sKLS0tIEExYVJ3R2dEdm5wZVN1UUhVVVVQ
            NmorQWs1RlRPb1RuQ1VnOVc2dkFiVFEKoyBbRUX0I75g9ujseppL6090DyirBXbC
            G8apMnBWlnMk32QssBVqLNYb8FBCaITR++V7HWIH81JVYfwzAoQqaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T05:16:25Z"
    mac: ENC[AES256_GCM,data:PXhplAp4Tz3OwjEGeVxnaAO0lO/UBbK3KwJAAxP/M/5V9WV9tjwB2GrawZa/K2B9Il6L3OCaUwyB4kT8u4QNyS77TQmoA+yVNAFnb251YduCp8vdeoXnM6KcK6KLmCn+vIj/MSVuDBPPWyNVVhfk/8L2UAfMOT0HoFCss2vXPsk=,iv:8ULASi4A3+rNNzzPoXKdd308VIFppaPK+YYOW0+iv5E=,tag:VeeYGvOGriL53dtviE+PVQ==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-db-config
    namespace: firefly-iii
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:D7e9rm0hEQ==,iv:ZtF9LWxHYoFg6FxPeVsrRPG3s7rNq+YzD15npOdVjI4=,tag:s58eaNOc9SurmFl1JGnjiQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:cZrvoYUUU/Iixbu1YWDQTRfravHX7qITTp9bDQ==,iv:iDNQioZKqKhVnc8BPz3UycmyWhNxg2RU1h/H+e1EWwQ=,tag:yEAV3yL7qBVmXACf2ag5hA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:/6IKcR9igw==,iv:A9NQbzTSENiqIX1q+xIHnRbf0iABpE3IUng3C68CgjQ=,tag:H311/qHCv7mOsJ5T71WKrw==,type:str]
    PGPASSWORD: ENC[AES256_GCM,data:24xgwm7NBTtCFoD+npRsAJPP1Na++SCO58XvBw==,iv:c1AcmiKEzJF8D+WZ5ys5977vdpEMFsUkkbBpsyfM8AY=,tag:IWB2H4cqTajAi90R5EgJ+g==,type:str]
    DBHOST: ENC[AES256_GCM,data:MRT+QFHF6z47SgE9ePMP4ODkiTcCsA==,iv:uiNNDbtfYzyR3PDrieSqQNeXqJUA/imhJaeuS/n05bs=,tag:Vp2Ys+97o7II1BiPqGrLUw==,type:str]
    DBPORT: ENC[AES256_GCM,data:WX6XAg==,iv:u4HEVlg22ZgvwAmkuNimcun2Ao3+kuBwbxBonqMvNLg=,tag:+cuGrNnk1kLD+v8ejOs8qA==,type:str]
    DBNAME: ENC[AES256_GCM,data:tQAsgbpNyQ==,iv:ajT4Sk16Y9xoOwURcpvUyLpb8F4kGdxEK+PfEK0w6ug=,tag:0twPCCW9lo+gu3dsoKSIaA==,type:str]
    DBUSER: ENC[AES256_GCM,data:aUYdkgL8tg==,iv:EKIJzt6D8XG/aRMrNcrSZe+vXCVEqiD6khC39pmwtq0=,tag:MIP9z2cTPAgqdiLjvM11dw==,type:str]
    TZ: ENC[AES256_GCM,data:ql12qLogGgY2Y+QDqAyTGro=,iv:4666fDznJrDtuEQBASC/XPuOazhsNOzYGVyeocndDBU=,tag:+lGAa+dCTHq/6W+sBZnx7g==,type:str]
    BACKUP_ENABLED: ENC[AES256_GCM,data:ABiL3w==,iv:j8asWBTiCd8091FUJ64mNyhH7NQsqcIG87HQ3AKYH08=,tag:iz12qS14RVL9MyCDpJqsuA==,type:str]
    RESTORE_ENABLED: ENC[AES256_GCM,data:1bx12Vk=,iv:Z2V65f68Bx1/rMdqioTeZz4CDPWEq+fPN8mg9FnE94c=,tag:9bj3SLFTJ02CtDQ6wkR3QQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyajIzYitrdVcvWTZFZE84
            WWh2Ymt5bWdlVHFpRzc5QllMR2ljd2h5eFIwCmpEeUlzcGhJNmdDR1pRaWw1VTB0
            MzcrVUl4QWRraFZNY1RJSUlVUFBOT2sKLS0tIEExYVJ3R2dEdm5wZVN1UUhVVVVQ
            NmorQWs1RlRPb1RuQ1VnOVc2dkFiVFEKoyBbRUX0I75g9ujseppL6090DyirBXbC
            G8apMnBWlnMk32QssBVqLNYb8FBCaITR++V7HWIH81JVYfwzAoQqaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T05:16:25Z"
    mac: ENC[AES256_GCM,data:PXhplAp4Tz3OwjEGeVxnaAO0lO/UBbK3KwJAAxP/M/5V9WV9tjwB2GrawZa/K2B9Il6L3OCaUwyB4kT8u4QNyS77TQmoA+yVNAFnb251YduCp8vdeoXnM6KcK6KLmCn+vIj/MSVuDBPPWyNVVhfk/8L2UAfMOT0HoFCss2vXPsk=,iv:8ULASi4A3+rNNzzPoXKdd308VIFppaPK+YYOW0+iv5E=,tag:VeeYGvOGriL53dtviE+PVQ==,type:str]
    version: 3.13.2
