apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:9XsOZHRlZniIIh6c+/4w9A==,iv:t2FzmI9NqBbQUnChdKS7wTgYZ/BIl+wYOcuFScDOYfQ=,tag:kJ23TJevGIFdnZQEecztew==,type:str]
    admin-user: ENC[AES256_GCM,data:N3OZhhXlZyk=,iv:ouNPK+9UYNOHYafnYPR57/CuvRkCToNWPxEmLQXqiso=,tag:sv7qhiJF3TSJI3vPei1Sww==,type:str]
kind: Secret
metadata:
    name: admin-creds
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcDRySjdSTkZqdDVRMXNx
            RnB4NlloK0kxOERPdkJMMmU4S3NoUUFNWTNRCkJlck10bXBaR01KUTUyK3VNd0x1
            dUM0Yklvb096QjYrV1dZWHIyN0hYRGcKLS0tIE9FMDZEUVI1dmNsaGdEdlhZYVNs
            SHp1S3o2M0dWbWhLUGpXYmFtVUJMSEUKlkHN9UuyNZXvVRc8MRasS0DyzDX7j03y
            oCjmnbz5/m7rUDTFqnEGKWC5eQ2XdzW4GG6S12p9hVUVcPCrdwe1jA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T11:52:26Z"
    mac: ENC[AES256_GCM,data:44UzGlgz7d2+hAKFqHwxc/VKCTCAemRNAmXNdgGAoK8pt3GrgMYGtykW4CEyG88stSqCI3Gj6djAFF1k2y0Om4Q/bQ3U1X7daPBWaHzET1EhBqoYdrCX/3zRx1r9ugc0SS/AAjArg6E1is44OuZOR8ddLvekerix3kuiolAfk88=,iv:zI3tP23tmB1wOD0eY82VnrgQoYazUYo+jHxwWNcbwfA=,tag:xA86ADMRvPJhbOdP6nNTiQ==,type:str]
    version: 3.13.2
