apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:YDxQxH62UO6mZbC+v4EQvQ==,iv:cSHww+sHfmxybwBLQFp1u5bvd2XI/e7+YjUD92cOaZw=,tag:Pj1btgstWlf6Z9/iLCI12Q==,type:str]
    admin-user: ENC[AES256_GCM,data:bDrNctYaRVU=,iv:UHPeh74zGf5ENic+oFIfkEWrxBnrLBSfM9lp1dDkCMY=,tag:rhZoj8+XHEZMAi3IiODvmQ==,type:str]
kind: Secret
metadata:
    name: admin-creds
type: Opaque
sops:
    age:
        - recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM3Bjck5WSDd4azJ0YkFs
            NnVRUmJIV2VvdUVjWjZTWXFKa2Qxajhid3hVClhvd2Y0KzMyVTdRaERqTzZTQzND
            VlZkek9ZUEtSRTViMHI3V1UzTVRqSkkKLS0tIGo5dUE1VDZSUkt0QXpSTjF3bTIz
            SHpYQkRiQkFZdlZPMXdpdlAwa09qc0EK512s07xidrd5ITowbA+pk/0KlK05898F
            2AlR0aZa1xlYKq0UXkl8nsZDD6V2iCa3w4xR+2nmQsxS+Jaah+T1Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T08:08:30Z"
    mac: ENC[AES256_GCM,data:XXYTdrdzR+tahohNOkS44OIDpNLyKzDicvNfu9X/qnNnTDQ5beGGS3cY7MNM+JhM1LJjyTvJ3URq4fJ6MjZRHCvxvUO8uTUK3Wh5W89Vu0PZwBFTNL2w03d2oLaJlRAxVAlNsNAYwnrN5VHaFu8oYOn9XdfuP85geK5oJfnqvuU=,iv:NdpGPCA39oOoOyDT3UeOIAVyrR9UumMicL8AFmmgE/U=,tag:6XWuWdt8+CRCfNYpRi9A4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
