apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        runAsNonRoot: true
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.45.0
        ports:
        - containerPort: 9090
        envFrom:
        - secretRef:
            name: linkding-credentials
        volumeMounts:
        - name: linkding-pv
          mountPath: /etc/linkding/data
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: linkding-pv
        persistentVolumeClaim:
          claimName: linkding-data-pvc
