apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: linkding
        image: sissbruecker/linkding:1.45.0
        ports:
        - containerPort: 9090
        livenessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - secretRef:
            name: linkding-credentials
        volumeMounts:
        - name: linkding-pv
          mountPath: /etc/linkding/data
        resources:
          requests:
            memory: 128Mi
            cpu: 1m
          limits:
            memory: 256Mi
      volumes:
      - name: linkding-pv
        persistentVolumeClaim:
          claimName: linkding-data-pvc
