apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1.5Gi
  local:
    path: /mnt/linkding-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          key: kubernetes.io/hostname
          operator: In
          values:
          - master
