apiVersion: v1
data:
    LD_DB_ENGINE: ENC[AES256_GCM,data:X/+yb5EpzeX6tKEY,iv:1HBUSjDG0sHRt0RWQljKOmxoBOkiEfkOfQGhK9zjwkY=,tag:cI0pnv1BIC9EhokyJHhzrw==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:rgg+Hv5JUqrSQ4sy7/DXiw==,iv:nOxceRJjgmz6/ewk89ixmUXwZLKYdDk7wHDlpJeodsI=,tag:qoRwjhBDV2IUNC9DVdmGWw==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:U7nvnaMDxB2JgKnWIMUrZA==,iv:1grTKN4tUpD5AaQu3/YaDCmJLZBeArRBS4qhqE4HRiw=,tag:BaXnXXe6SKTxUAGL7CPIEA==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:pUlDP+/+ouw=,iv:w+8w+fq9lWqihLtm7OeNSfVEPt3kBaVaKOtj6fTFxoc=,tag:xau9rBbhuPfjotcME7+nxA==,type:str]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:hMdg3V33/PCmyYA8,iv:AUuN+oqtpFB28JVmDZMEZHxdlZOM0oKpDBIusBuw2yA=,tag:rvnT4s5+rry9XmsPEhengg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rY13GU2hEH6n72WCwJHR0Q==,iv:cheqjntpkCCzKxCNVi6aovfs0aD54cGFCRhfE9Kl8Ps=,tag:qrb9wKqHV2Rzdm73QTd+BQ==,type:str]
kind: Secret
metadata:
    name: linkding-credentials
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQWZsdGNadzEzWnJCZmxT
            VWdoZitJaFBxR1VPaEdMUGhNS2wzRER6bEZFCmVJU09WWHcrS1J2dTFSc1FMZFZG
            ZE9UbTdQL0RtMGFBanNMUHNrVEhOTUkKLS0tIHBDcUpJd0Q5TlM2a1paMEFWeUJk
            SG5URTcvRjN0SEpyZDloUzVMem9NNDgKPMCb5nrr3WYakpBF+GX/+psKgdOSyX4p
            riUZZSWDoe6zSPQYTK14/qKX7YOR4DavyhULdhuD5QjG67stIdyy1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:34:59Z"
    mac: ENC[AES256_GCM,data:xEaXgeESYlbC6lY3zcyzcukbyoX7HTvubUVwE6TqqrvORBAEB3qszr/SgrTL+XlvtFIs6tkR2cH2eakUjKQL0sazYRdvR2gp8eKuoEdhMAQDBMPuKTtAByV8l/pNKeiLgc+5hTyAGOndgzG09qoWhc6jIF6NXWOT7IWi+09Alns=,iv:r1WO8KzRUY86AgnxOMURiNxSrmLvxT6UUjbCdtqMqUQ=,tag:OxNxE26gndgcxTf5gM7iFg==,type:str]
    version: 3.13.2
# ---
apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:jHwL+fKiLUhJyS7E,iv:rylAlsYS1pz/Pnj+epmxtcMmd1QuahnJSDym0szEdF0=,tag:sLGVKGOXLWSa4BsmJ25tIw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:loEwIBwU0fAwN2RKsjiDMA==,iv:7rXfrwe5lHicn9t3h8HKB0CVC81NLr3gegG2SL8hvGg=,tag:DVxrKw2F4KWnQEHQxIVP9g==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:DV/+m+/gJqkiabFC,iv:U5mMLIFkl747aTAjjTdqf7+wxubxb02SC7ey09EXXAE=,tag:ZgBYai7JpKc1mzaWcUUYOw==,type:str]
kind: Secret
metadata:
    name: linkding-postgres-secret
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcU9sc1ZzK3pSb2lPbWYv
            ZGRKSzdQMGZFQnBGV1RORFBnelBVWVRyWmdFCkx3enBzWHVyM3MzN2RRaVNhRWdt
            TjRVYm9IMmpudFhiS0dPNVNUb2sxcXMKLS0tIDQyOTBIa1hUYU9nQXgxelZPSzQy
            eGx3SFVqN1J2c005KzkvNmhUWnEzUm8KgXyIHbe2gZ+fHpGBo1a6c5/3269zaJga
            bOBE5TWLb4xZejoCV/59BIsLmB/qUaAOFdrZEKZR9MUb9zXv8i7oUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ds6qamqxum2g45umd2pwa5dad62fjqpfdjzt324f363e9evd8vvs7yjd75
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T18:15:59Z"
    mac: ENC[AES256_GCM,data:2BhSZbnFJLreoZ/RSFicbixXHNYpdPF7j4nP3TJ+2GIghmuSepbCZi1tTuO7GPPBbXyN6eEVOdYRh2bohzOjHq3sNsonO2m13RF65o8j86ny9VuX0yF42IJngV8jFmLjEr8daZM4Wf2bBMzSVNdPTWYz39fciHuJLLudRe6PQRo=,iv:+EtrPuPDybvFuMwVByFAaXtwxFLU9Lx5C+/VMtQ/ozM=,tag:Cim5HIC2aj0+1l+6D409lA==,type:str]
    version: 3.13.2
