apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkding-db
spec:
  serviceName: linkding-db
  replicas: 1
  selector:
    matchLabels:
      app: linkding-db
  template:
    metadata:
      labels:
        app: linkding-db
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres
        image: postgres:18-alpine@sha256:4f9ced003ba58a854656ba150d146243d27ae3ac
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: linkding-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
