apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: linkding-db
spec:
  serviceName: linkding-db
  replicas: 1
  selector:
    matchLabels:
      app: linkding-db
  template:
    metadata:
      labels:
        app: linkding-db
    spec:
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 70
        runAsGroup: 70
        fsGroup: 70
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: postgres
        image: postgres@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15 # Postgres 18-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: linkding-postgres-secret
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        readinessProbe:
          exec:
            command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
          initialDelaySeconds: 30
          periodSeconds: 10
      # volumes:
      # - name: postgres-data
      #   persistentVolumeClaim:
      #     claimName: postgres-pvc
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-k8s-cluster
        resources:
          requests:
            storage: 1Gi
