apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: renovate
            image: renovate/renovate:43
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 100m
                memory: 4Gi
              limits:
                memory: 6Gi
            args:
            - edvsul/k8s-cluster

            envFrom:
            - secretRef:
                name: renovate-container-env
            - configMapRef:
                name: renovate-configmap
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never 
